general:
  branches:
    ignore:
      - gh-pages

machine:
  ruby:
    version: 2.4

dependencies:
  override:
    # http://stackoverflow.com/a/31032379
    - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

test:
  post:
    # https://github.com/gjtorikian/html-proofer
    - bundle exec htmlproof . --disable-external --alt-ignore '/.*/' --file-ignore /.*vendor\/bundle*/
